Cake.create(name: "Chocolate Cake", description: "A rich and decadent chocolate cake.", price: 9.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Vanilla Delight", description: "A classic vanilla cake with creamy frosting.", price: 8.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Red Velvet Bliss", description: "A moist red velvet cake with cream cheese frosting.", price: 10.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Lemon Zest Cake", description: "A zesty lemon cake with lemon glaze.", price: 7.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Carrot Paradise", description: "A spiced carrot cake with cream cheese frosting.", price: 9.49, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Fruit Explosion", description: "A fruit-filled cake bursting with flavors.", price: 11.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Cookies & Cream Delight", description: "Chocolate chip cookie cake with Oreo cream.", price: 12.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Rainbow Dream", description: "A colorful rainbow cake for a joyful celebration.", price: 14.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Pineapple Paradise", description: "A tropical pineapple upside-down cake.", price: 9.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Strawberry Sensation", description: "A strawberry shortcake with fresh strawberries.", price: 8.49, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Coconut Cream Pie", description: "A coconut cake with creamy coconut frosting.", price: 10.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Black Forest Fantasy", description: "A decadent Black Forest cake with cherries.", price: 11.49, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Coffee Tiramisu", description: "Espresso-soaked cake layers with mascarpone.", price: 13.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Peanut Butter Perfection", description: "A peanut butter lover's dream cake.", price: 10.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Mango Tango", description: "A tropical mango-flavored cake with fresh mangoes.", price: 12.49, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Raspberry Romance", description: "Raspberry-infused cake with raspberry compote.", price: 10.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Caramel Swirl", description: "A rich caramel cake with caramel drizzle.", price: 9.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Hazelnut Heaven", description: "A hazelnut cake with Nutella frosting.", price: 11.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Blueberry Bliss", description: "Blueberry-filled cake with blueberry glaze.", price: 8.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Oreo Overload", description: "An Oreo lover's delight with crushed Oreos.", price: 12.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Lavender Love", description: "Lavender-infused cake with a lavender glaze.", price: 10.49, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Almond Amaretto", description: "Almond cake with amaretto-infused frosting.", price: 13.49, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Minty Madness", description: "Mint chocolate cake with minty cream.", price: 11.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Cherry Cheesecake", description: "Cheesecake with cherry topping.", price: 14.99, image_url: "https://picsum.photos/200/300")
Cake.create(name: "Pistachio Pleasure", description: "Pistachio-flavored cake with pistachio frosting.", price: 11.99, image_url: "https://picsum.photos/200/300")
